#!/bin/bash
sudo apt-get update
sudo apt-get --yes install openssh-server
sudo apt-get --yes install tmux
sudo apt-get --yes install vim
#sudo apt-get install motion
sudo apt-get --yes install arp-scan
sudo apt-get --yes install apt-file
sudo apt-get --yet install crudini
sudo apt-get --yet install neofetch
sudo apt-get autoremove
ssh-keygen
